### ISSUE TITLE
Detailed Codebook

### ISSUE THREAD

**Issue by LuZhang0128** [zumbov2/swissparl#1]
Hi David,

I wonder what does each variable in the Business dataset means? For instance the InitialSituation and Proceedings. Is there a more detailed codebook for this dataset? Thank you so much!

Best,
Lu

**Comment by zumbov2** [comment]
Hi Lu,

Thank you very much for your question. Unfortunately there is no official codebook at the moment, because the API is still unofficial. According to the website of the Swiss parliament, the official version of the web services should go live in spring 2021. Let's hope that a detailed codebook will be available then. 

I will link it here asap.

Best, 
David
